resource "aws_s3_bucket" "audio" {
  bucket        = var.bucket_name
  force_destroy = true # allows terraform destroy even if objects remain

  tags = var.tags
}

resource "aws_s3_bucket_cors_configuration" "audio" {
  bucket = aws_s3_bucket.audio.id

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods  = ["PUT", "GET"]
    allowed_origins  = var.cors_allowed_origins
    max_age_seconds  = 3000
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "audio" {
  bucket = aws_s3_bucket.audio.id

  rule {
    id     = "AutoDeleteTempAudio"
    status = "Enabled"

    filter {} # applies to all objects in the bucket

    expiration {
      days = var.expiration_days
    }
  }
}

# Block all public access — the bucket is only ever reached via
# presigned URLs generated by the Lambdas, never browsed directly.
resource "aws_s3_bucket_public_access_block" "audio" {
  bucket = aws_s3_bucket.audio.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls       = true
  restrict_public_buckets  = true
}
